#!/bin/bash
################################################################################
# generate-apparmor.sh - Generador automatizado de perfiles AppArmor
# Autor: POETUX Security Team
# Filosofía: "Cada permiso innecesario es un bug"
################################################################################

set -euo pipefail

################################################################################
# === Colores y Output ===
################################################################################

readonly RED='\e[31m'
readonly GREEN='\e[32m'
readonly YELLOW='\e[33m'
readonly BLUE='\e[34m'
readonly CYAN='\e[36m'
readonly RESET='\e[0m'

print_success() { echo -e "${GREEN}[✔]${RESET} $*"; }
print_error() { echo -e "${RED}[✗]${RESET} $*" >&2; }
print_warning() { echo -e "${YELLOW}[⚠]${RESET} $*"; }
print_info() { echo -e "${BLUE}[ℹ]${RESET} $*"; }
print_step() { echo -e "${CYAN}[→]${RESET} $*"; }

################################################################################
# === Verificaciones de Seguridad ===
################################################################################

check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "Este script requiere privilegios root"
        print_info "Ejecuta: sudo $0 $*"
        exit 1
    fi
}

check_apparmor() {
    if ! systemctl is-active --quiet apparmor; then
        print_error "AppArmor no está activo"
        print_info "Activa AppArmor: sudo systemctl start apparmor"
        exit 1
    fi
    
    if ! command -v aa-genprof &> /dev/null; then
        print_error "apparmor-utils no está instalado"
        print_info "Instala: sudo apt install apparmor-utils"
        exit 1
    fi
    
    print_success "AppArmor activo y herramientas disponibles"
}

################################################################################
# === Funciones de Utilidad ===
################################################################################

find_binary() {
    local app_name="$1"
    local binary_path
    
    # Buscar en ubicaciones comunes
    for path in \
        "/usr/bin/${app_name}" \
        "/usr/local/bin/${app_name}" \
        "/opt/${app_name}/${app_name}" \
        "/snap/bin/${app_name}" \
        "$(command -v "${app_name}" 2>/dev/null)"
    do
        if [[ -x "$path" ]]; then
            binary_path="$path"
            break
        fi
    done
    
    if [[ -z "${binary_path:-}" ]]; then
        print_error "No se encontró el binario: $app_name"
        print_info "Rutas verificadas:"
        print_info "  - /usr/bin/${app_name}"
        print_info "  - /usr/local/bin/${app_name}"
        print_info "  - /opt/${app_name}/${app_name}"
        return 1
    fi
    
    echo "$binary_path"
}

get_profile_name() {
    local binary_path="$1"
    # Convertir /usr/bin/cursor → usr.bin.cursor
    echo "$binary_path" | sed 's|^/||; s|/|.|g'
}

################################################################################
# === Generación de Perfil Base ===
################################################################################

generate_base_profile() {
    local binary_path="$1"
    local profile_name="$2"
    local profile_path="/etc/apparmor.d/${profile_name}"
    
    print_step "Generando perfil base para: $binary_path"
    
    # Crear perfil base manualmente (aa-genprof es interactivo)
    cat > "$profile_path" << EOF
# AppArmor profile for $(basename "$binary_path")
# Generated by POETUX Security Tools
# Date: $(date '+%Y-%m-%d %H:%M:%S')

#include <tunables/global>

$binary_path flags=(complain) {
  #include <abstractions/base>
  #include <abstractions/nameservice>
  #include <abstractions/fonts>
  #include <abstractions/X>
  #include <abstractions/freedesktop.org>
  #include <abstractions/user-tmp>

  # Capability restrictions
  # FILOSOFÍA: Denegar todas las capabilities por defecto
  # Solo añadir las estrictamente necesarias tras análisis
  capability setuid,
  capability setgid,
  
  # Binary execution
  $binary_path mr,
  
  # Shared libraries
  /usr/lib/** rm,
  /lib/** rm,
  
  # Configuration
  /etc/ld.so.cache r,
  /etc/localtime r,
  
  # User home (limitado)
  owner @{HOME}/.config/** rw,
  owner @{HOME}/.cache/** rw,
  owner @{HOME}/.local/share/** rw,
  
  # Deny sensitive paths
  deny @{HOME}/.ssh/** rw,
  deny @{HOME}/.gnupg/** rw,
  deny /etc/shadow r,
  deny /etc/gshadow r,
  deny /root/** rw,
  
  # Proc filesystem (minimal)
  @{PROC}/sys/kernel/random/uuid r,
  @{PROC}/*/stat r,
  @{PROC}/*/status r,
  owner @{PROC}/*/fd/ r,
  
  # Dev filesystem (minimal)
  /dev/null rw,
  /dev/zero r,
  /dev/urandom r,
  /sys/devices/system/cpu/** r,
  
  # Network (si es necesario)
  network inet stream,
  network inet6 stream,
  network inet dgram,
  network inet6 dgram,
  network netlink raw,
  
  # DBus
  dbus send,
  dbus receive,
}
EOF
    
    print_success "Perfil base creado: $profile_path"
    print_warning "Perfil en modo COMPLAIN (aprendizaje)"
}

################################################################################
# === Modo Aprendizaje ===
################################################################################

learning_mode() {
    local binary_path="$1"
    local profile_name="$2"
    local profile_path="/etc/apparmor.d/${profile_name}"
    
    print_step "Cargando perfil en modo aprendizaje..."
    apparmor_parser -r "$profile_path"
    
    print_info ""
    print_info "═══════════════════════════════════════════════════════"
    print_info "  MODO APRENDIZAJE ACTIVADO"
    print_info "═══════════════════════════════════════════════════════"
    print_info ""
    print_info "El perfil AppArmor está en modo COMPLAIN."
    print_info "Todas las violaciones se registrarán pero NO se bloquearán."
    print_info ""
    print_info "INSTRUCCIONES:"
    print_info "1. Ejecuta la aplicación: $binary_path"
    print_info "2. Usa TODAS sus características:"
    print_info "   - Abre archivos de diferentes ubicaciones"
    print_info "   - Usa todas las funciones principales"
    print_info "   - Accede a configuraciones"
    print_info "   - Prueba extensiones/plugins si aplica"
    print_info "3. Cierra la aplicación cuando hayas terminado"
    print_info ""
    print_info "Los accesos se registrarán en: /var/log/audit/audit.log"
    print_info "                            y: /var/log/kern.log"
    print_info ""
    
    read -p "Presiona Enter para continuar después de probar la aplicación..."
    
    print_success "Modo aprendizaje completado"
}

################################################################################
# === Análisis de Logs y Refinamiento ===
################################################################################

analyze_logs() {
    local profile_name="$1"
    local profile_path="/etc/apparmor.d/${profile_name}"
    
    print_step "Analizando logs de AppArmor..."
    
    # Verificar si hay entradas en audit.log
    if [[ -f /var/log/audit/audit.log ]]; then
        local audit_count=$(grep -c "apparmor.*ALLOWED.*profile=\"${profile_name}\"" /var/log/audit/audit.log 2>/dev/null || echo "0")
        print_info "Eventos en audit.log: $audit_count"
    fi
    
    # Verificar kern.log
    if [[ -f /var/log/kern.log ]]; then
        local kern_count=$(grep -c "apparmor.*ALLOWED.*profile=\"${profile_name}\"" /var/log/kern.log 2>/dev/null || echo "0")
        print_info "Eventos en kern.log: $kern_count"
    fi
    
    print_info ""
    print_info "Ejecutando aa-logprof para refinar el perfil..."
    print_warning "aa-logprof es interactivo - responde 'A' para Allow cuando sea necesario"
    print_info ""
    
    # aa-logprof procesará los logs y permitirá añadir reglas
    if aa-logprof -d /etc/apparmor.d; then
        print_success "Perfil refinado con aa-logprof"
    else
        print_warning "aa-logprof finalizado (revisa cambios manualmente)"
    fi
}

################################################################################
# === Aplicar Modo Enforce ===
################################################################################

apply_enforce() {
    local profile_name="$1"
    local profile_path="/etc/apparmor.d/${profile_name}"
    
    print_step "Cambiando perfil a modo ENFORCE..."
    
    # Cambiar flags=(complain) a flags=(enforce)
    sed -i 's/flags=(complain)/flags=(enforce)/' "$profile_path"
    
    # Recargar perfil
    apparmor_parser -r "$profile_path"
    
    # Verificar estado
    if aa-status | grep -q "$profile_name.*enforce"; then
        print_success "Perfil en modo ENFORCE"
    else
        print_error "Fallo al aplicar modo enforce"
        return 1
    fi
}

################################################################################
# === Optimización del Perfil ===
################################################################################

optimize_profile() {
    local profile_path="$1"
    local app_name="$2"
    
    print_step "Optimizando perfil para: $app_name"
    
    # Añadir reglas específicas según el tipo de aplicación
    case "$app_name" in
        cursor|code|vscode)
            print_info "Aplicación: Editor de código"
            # Añadir reglas para editores
            cat >> "$profile_path" << 'EOF'

  # Editor de código: acceso a proyectos
  owner @{HOME}/Projects/** rw,
  owner @{HOME}/Documents/** rw,
  owner @{HOME}/workspace/** rw,
  
  # Git
  /usr/bin/git rix,
  owner @{HOME}/.gitconfig r,
  
  # Node.js / NPM
  /usr/bin/node rix,
  /usr/bin/npm rix,
  owner @{HOME}/.npm/** rw,
  owner @{HOME}/.node-gyp/** rw,
EOF
            ;;
            
        brave|chrome|chromium|firefox)
            print_info "Aplicación: Navegador web"
            # Añadir reglas para navegadores
            cat >> "$profile_path" << 'EOF'

  # Navegador: descargas y multimedia
  owner @{HOME}/Downloads/** rw,
  owner @{HOME}/Pictures/** r,
  owner @{HOME}/Videos/** r,
  
  # GPU acceleration
  /dev/dri/** rw,
  /sys/devices/pci**/drm/** r,
  
  # Audio/Video
  /dev/snd/** rw,
  /dev/video* rw,
EOF
            ;;
    esac
    
    print_success "Perfil optimizado"
}

################################################################################
# === Función Principal ===
################################################################################

main() {
    local app_name="${1:-}"
    
    # Header
    echo ""
    print_info "═══════════════════════════════════════════════════════"
    print_info "  Generador de Perfiles AppArmor - POETUX"
    print_info "  Filosofía: Mínimo privilegio por diseño"
    print_info "═══════════════════════════════════════════════════════"
    echo ""
    
    # Verificaciones
    if [[ -z "$app_name" ]]; then
        print_error "Uso: $0 <nombre-aplicacion>"
        print_info "Ejemplo: $0 cursor"
        print_info "         $0 brave"
        exit 1
    fi
    
    check_root
    check_apparmor
    
    echo ""
    print_step "Aplicación objetivo: $app_name"
    
    # Encontrar binario
    local binary_path
    if ! binary_path=$(find_binary "$app_name"); then
        exit 1
    fi
    print_success "Binario encontrado: $binary_path"
    
    # Nombre del perfil
    local profile_name
    profile_name=$(get_profile_name "$binary_path")
    print_info "Nombre del perfil: $profile_name"
    
    # Verificar si ya existe
    local profile_path="/etc/apparmor.d/${profile_name}"
    if [[ -f "$profile_path" ]]; then
        print_warning "Ya existe un perfil en: $profile_path"
        read -p "¿Sobrescribir? (s/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Ss]$ ]]; then
            print_info "Operación cancelada"
            exit 0
        fi
        
        # Backup del perfil anterior
        cp "$profile_path" "${profile_path}.backup.$(date +%Y%m%d_%H%M%S)"
        print_info "Backup creado"
    fi
    
    echo ""
    
    # Generar perfil base
    generate_base_profile "$binary_path" "$profile_name"
    
    echo ""
    
    # Modo aprendizaje
    read -p "¿Iniciar modo aprendizaje? (S/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        learning_mode "$binary_path" "$profile_name"
        echo ""
        analyze_logs "$profile_name"
    fi
    
    echo ""
    
    # Optimizar perfil
    optimize_profile "$profile_path" "$app_name"
    
    echo ""
    
    # Aplicar enforce
    read -p "¿Aplicar modo ENFORCE ahora? (S/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        apply_enforce "$profile_name"
    else
        print_warning "Perfil permanece en modo COMPLAIN"
        print_info "Para activar enforce: sudo aa-enforce $profile_path"
    fi
    
    echo ""
    print_success "═══════════════════════════════════════════════════════"
    print_success "  PERFIL APPARMOR GENERADO Y APLICADO"
    print_success "═══════════════════════════════════════════════════════"
    echo ""
    print_info "Ubicación: $profile_path"
    print_info "Estado: $(aa-status | grep "$profile_name" | awk '{print $2}')"
    echo ""
    print_info "Comandos útiles:"
    print_info "  Ver estado: sudo aa-status | grep $app_name"
    print_info "  Logs: sudo grep apparmor.*$app_name /var/log/kern.log"
    print_info "  Modo complain: sudo aa-complain $profile_path"
    print_info "  Modo enforce: sudo aa-enforce $profile_path"
    print_info "  Deshabilitar: sudo aa-disable $profile_path"
    echo ""
}

# Ejecutar
main "$@"

